/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#ifndef J4A__tv_danmaku_android_log_BLog__H
#define J4A__tv_danmaku_android_log_BLog__H

#include "j4a/j4a_base.h"

void J4AC_tv_danmaku_android_log_BLog__v(JNIEnv *env, jstring tag, jstring message);
void J4AC_tv_danmaku_android_log_BLog__v__catchAll(JNIEnv *env, jstring tag, jstring message);
void J4AC_tv_danmaku_android_log_BLog__v__withCString(JNIEnv *env, const char *tag_cstr__, const char *message_cstr__);
void J4AC_tv_danmaku_android_log_BLog__v__withCString__catchAll(JNIEnv *env, const char *tag_cstr__, const char *message_cstr__);
void J4AC_tv_danmaku_android_log_BLog__d(JNIEnv *env, jstring tag, jstring message);
void J4AC_tv_danmaku_android_log_BLog__d__catchAll(JNIEnv *env, jstring tag, jstring message);
void J4AC_tv_danmaku_android_log_BLog__d__withCString(JNIEnv *env, const char *tag_cstr__, const char *message_cstr__);
void J4AC_tv_danmaku_android_log_BLog__d__withCString__catchAll(JNIEnv *env, const char *tag_cstr__, const char *message_cstr__);
void J4AC_tv_danmaku_android_log_BLog__i(JNIEnv *env, jstring tag, jstring message);
void J4AC_tv_danmaku_android_log_BLog__i__catchAll(JNIEnv *env, jstring tag, jstring message);
void J4AC_tv_danmaku_android_log_BLog__i__withCString(JNIEnv *env, const char *tag_cstr__, const char *message_cstr__);
void J4AC_tv_danmaku_android_log_BLog__i__withCString__catchAll(JNIEnv *env, const char *tag_cstr__, const char *message_cstr__);
void J4AC_tv_danmaku_android_log_BLog__w(JNIEnv *env, jstring tag, jstring message);
void J4AC_tv_danmaku_android_log_BLog__w__catchAll(JNIEnv *env, jstring tag, jstring message);
void J4AC_tv_danmaku_android_log_BLog__w__withCString(JNIEnv *env, const char *tag_cstr__, const char *message_cstr__);
void J4AC_tv_danmaku_android_log_BLog__w__withCString__catchAll(JNIEnv *env, const char *tag_cstr__, const char *message_cstr__);
void J4AC_tv_danmaku_android_log_BLog__e(JNIEnv *env, jstring tag, jstring message);
void J4AC_tv_danmaku_android_log_BLog__e__catchAll(JNIEnv *env, jstring tag, jstring message);
void J4AC_tv_danmaku_android_log_BLog__e__withCString(JNIEnv *env, const char *tag_cstr__, const char *message_cstr__);
void J4AC_tv_danmaku_android_log_BLog__e__withCString__catchAll(JNIEnv *env, const char *tag_cstr__, const char *message_cstr__);
int J4A_loadClass__J4AC_tv_danmaku_android_log_BLog(JNIEnv *env);

#define J4A_HAVE_SIMPLE__J4AC_tv_danmaku_android_log_BLog

#define J4AC_BLog__v J4AC_tv_danmaku_android_log_BLog__v
#define J4AC_BLog__v__catchAll J4AC_tv_danmaku_android_log_BLog__v__catchAll
#define J4AC_BLog__v__withCString J4AC_tv_danmaku_android_log_BLog__v__withCString
#define J4AC_BLog__v__withCString__catchAll J4AC_tv_danmaku_android_log_BLog__v__withCString__catchAll
#define J4AC_BLog__d J4AC_tv_danmaku_android_log_BLog__d
#define J4AC_BLog__d__catchAll J4AC_tv_danmaku_android_log_BLog__d__catchAll
#define J4AC_BLog__d__withCString J4AC_tv_danmaku_android_log_BLog__d__withCString
#define J4AC_BLog__d__withCString__catchAll J4AC_tv_danmaku_android_log_BLog__d__withCString__catchAll
#define J4AC_BLog__i J4AC_tv_danmaku_android_log_BLog__i
#define J4AC_BLog__i__catchAll J4AC_tv_danmaku_android_log_BLog__i__catchAll
#define J4AC_BLog__i__withCString J4AC_tv_danmaku_android_log_BLog__i__withCString
#define J4AC_BLog__i__withCString__catchAll J4AC_tv_danmaku_android_log_BLog__i__withCString__catchAll
#define J4AC_BLog__w J4AC_tv_danmaku_android_log_BLog__w
#define J4AC_BLog__w__catchAll J4AC_tv_danmaku_android_log_BLog__w__catchAll
#define J4AC_BLog__w__withCString J4AC_tv_danmaku_android_log_BLog__w__withCString
#define J4AC_BLog__w__withCString__catchAll J4AC_tv_danmaku_android_log_BLog__w__withCString__catchAll
#define J4AC_BLog__e J4AC_tv_danmaku_android_log_BLog__e
#define J4AC_BLog__e__catchAll J4AC_tv_danmaku_android_log_BLog__e__catchAll
#define J4AC_BLog__e__withCString J4AC_tv_danmaku_android_log_BLog__e__withCString
#define J4AC_BLog__e__withCString__catchAll J4AC_tv_danmaku_android_log_BLog__e__withCString__catchAll
#define J4A_loadClass__J4AC_BLog J4A_loadClass__J4AC_tv_danmaku_android_log_BLog

#endif//J4A__tv_danmaku_android_log_BLog__H
